#!/bin/sh
# Wi-Fi access point. Waits while /run/wifi.disabled exists (Wi-Fi switched
# off in logger.conf or over Bluetooth).
. /usr/libexec/canlogger/functions

if [ -e /run/wifi.disabled ]; then
	ip link set wlan0 down 2>/dev/null
	rm -f /run/wifi.ssid
	while [ -e /run/wifi.disabled ]; do sleep 1; done
fi

modprobe brcmfmac 2>/dev/null
if ! wait_for /sys/class/net/wlan0 10; then
	logger -t hostapd "no wlan0"
	sleep 10
	exit 1
fi

IP=$(conf wifi_ip 192.168.4.1)
SSID=$(conf wifi_ssid ET-18)
# wifi_psk (the 64-hex-digit key) takes precedence over the plain password
PSK=$(conf wifi_psk)
if [ -n "$PSK" ] && echo "$PSK" | grep -qE '^[0-9a-fA-F]{64}$'; then
	KEYLINE="wpa_psk=$PSK"
else
	[ -n "$PSK" ] && logger -t hostapd "wifi_psk must be 64 hex digits, ignoring it"
	PASS=$(conf wifi_password canlogger)
	if [ ${#PASS} -lt 8 ] || [ ${#PASS} -gt 63 ]; then
		logger -t hostapd "wifi_password must have 8 to 63 characters, using 'canlogger'"
		PASS=canlogger
	fi
	KEYLINE="wpa_passphrase=$PASS"
fi

ip addr flush dev wlan0
ip addr add "$IP/24" dev wlan0
ip link set wlan0 up

umask 077
cat > /run/hostapd.conf <<EOC
interface=wlan0
driver=nl80211
ssid=$SSID
country_code=$(conf wifi_country IT)
ieee80211d=1
hw_mode=g
channel=$(conf wifi_channel 6)
ieee80211n=1
wmm_enabled=1
auth_algs=1
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
$KEYLINE
EOC
echo "$SSID" > /run/wifi.ssid
hostapd /run/hostapd.conf 2>&1 | logger -t hostapd
